/****************************************************************************************************
 * arch/arm/src/artosyn/chip/ar_tim.h
 *
 *   Copyright (C) 2016 Gregory Nutt. All rights reserved.
 *   Authors: Gregory Nutt <gnutt@nuttx.org>
 *            David Sidrane <david_s5@nscdg.com>
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
 * 3. Neither the name NuttX nor the names of its contributors may be
 *    used to endorse or promote products derived from this software
 *    without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
 * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
 * AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 ****************************************************************************************************/

#ifndef __ARCH_ARM_SRC_ARTOSYN_CHIP_AR_TIM_H
#define __ARCH_ARM_SRC_ARTOSYN_CHIP_AR_TIM_H

/************************************************************************************
 * Included Files
 ************************************************************************************/

#include <nuttx/config.h>
#include "chip.h"
#include "ar_memorymap.h"


/****************************************************************************************************
 * Pre-processor Definitions
 ****************************************************************************************************/

/* Register Offsets *********************************************************************************/

/* Artosyn Timers - TIM0 ~ TIM23 */
#define AR_TIM_TIMER0LOADCOUNT_OFFSET       0x00  /* Value to be loaded into Timer0 */
#define AR_TIM_TIMER1LOADCOUNT_OFFSET       0x14  /* Value to be loaded into Timer1 */
#define AR_TIM_TIMER2LOADCOUNT_OFFSET       0x28  /* Value to be loaded into Timer2 */
#define AR_TIM_TIMER3LOADCOUNT_OFFSET       0x3C  /* Value to be loaded into Timer3 */
#define AR_TIM_TIMER4LOADCOUNT_OFFSET       0x50  /* Value to be loaded into Timer4 */
#define AR_TIM_TIMER5LOADCOUNT_OFFSET       0x64  /* Value to be loaded into Timer5 */
#define AR_TIM_TIMER6LOADCOUNT_OFFSET       0x78  /* Value to be loaded into Timer6 */
#define AR_TIM_TIMER7LOADCOUNT_OFFSET       0x8C  /* Value to be loaded into Timer7 */

#define AR_TIM_TIMER0LOADCOUNT2_OFFSET      0xB0  /* Value to be loaded into Timer0 */
#define AR_TIM_TIMER1LOADCOUNT2_OFFSET      0xB4  /* Value to be loaded into Timer1 */
#define AR_TIM_TIMER2LOADCOUNT2_OFFSET      0xB8  /* Value to be loaded into Timer2 */
#define AR_TIM_TIMER3LOADCOUNT2_OFFSET      0xBC  /* Value to be loaded into Timer3 */
#define AR_TIM_TIMER4LOADCOUNT2_OFFSET      0xC0  /* Value to be loaded into Timer4 */
#define AR_TIM_TIMER5LOADCOUNT2_OFFSET      0xC4  /* Value to be loaded into Timer5 */
#define AR_TIM_TIMER6LOADCOUNT2_OFFSET      0xC8  /* Value to be loaded into Timer6 */
#define AR_TIM_TIMER7LOADCOUNT2_OFFSET      0xCC  /* Value to be loaded into Timer7 */

#define AR_TIM_TIMER0CURRENTVALUE_OFFSET    0x04  /* Current Value of Timer0 (32-bit) */
#define AR_TIM_TIMER1CURRENTVALUE_OFFSET    0x18  /* Current Value of Timer1 (32-bit) */
#define AR_TIM_TIMER2CURRENTVALUE_OFFSET    0x2C  /* Current Value of Timer2 (32-bit) */
#define AR_TIM_TIMER3CURRENTVALUE_OFFSET    0x40  /* Current Value of Timer3 (32-bit) */
#define AR_TIM_TIMER4CURRENTVALUE_OFFSET    0x54  /* Current Value of Timer4 (32-bit) */
#define AR_TIM_TIMER5CURRENTVALUE_OFFSET    0x68  /* Current Value of Timer5 (32-bit) */
#define AR_TIM_TIMER6CURRENTVALUE_OFFSET    0x7C  /* Current Value of Timer6 (32-bit) */
#define AR_TIM_TIMER7CURRENTVALUE_OFFSET    0x90  /* Current Value of Timer7 (32-bit) */

#define AR_TIM_TIMER0CONTROLREG_OFFSET      0x08  /* Control Register for Timer0 */
#define AR_TIM_TIMER1CONTROLREG_OFFSET      0x1C  /* Control Register for Timer1 */
#define AR_TIM_TIMER2CONTROLREG_OFFSET      0x30  /* Control Register for Timer2 */
#define AR_TIM_TIMER3CONTROLREG_OFFSET      0x44  /* Control Register for Timer3 */
#define AR_TIM_TIMER4CONTROLREG_OFFSET      0x58  /* Control Register for Timer4 */
#define AR_TIM_TIMER5CONTROLREG_OFFSET      0x6C  /* Control Register for Timer5 */
#define AR_TIM_TIMER6CONTROLREG_OFFSET      0x80  /* Control Register for Timer6 */
#define AR_TIM_TIMER7CONTROLREG_OFFSET      0x94  /* Control Register for Timer7 */

#define AR_TIM_TIMER0EOI_OFFSET             0x0C  /* Clears the interrupt from Timer0 */
#define AR_TIM_TIMER1EOI_OFFSET             0x20  /* Clears the interrupt from Timer1 */
#define AR_TIM_TIMER2EOI_OFFSET             0x34  /* Clears the interrupt from Timer2 */
#define AR_TIM_TIMER3EOI_OFFSET             0x48  /* Clears the interrupt from Timer3 */
#define AR_TIM_TIMER4EOI_OFFSET             0x5C  /* Clears the interrupt from Timer4 */
#define AR_TIM_TIMER5EOI_OFFSET             0x70  /* Clears the interrupt from Timer5 */
#define AR_TIM_TIMER6EOI_OFFSET             0x84  /* Clears the interrupt from Timer6 */
#define AR_TIM_TIMER7EOI_OFFSET             0x98  /* Clears the interrupt from Timer7 */

#define AR_TIM_TIMER0INTSTATUS_OFFSET       0x10  /* Contains the interrupt status for Timer0 */
#define AR_TIM_TIMER1INTSTATUS_OFFSET       0x24  /* Contains the interrupt status for Timer1 */
#define AR_TIM_TIMER2INTSTATUS_OFFSET       0x38  /* Contains the interrupt status for Timer2 */
#define AR_TIM_TIMER3INTSTATUS_OFFSET       0x4C  /* Contains the interrupt status for Timer3 */
#define AR_TIM_TIMER4INTSTATUS_OFFSET       0x60  /* Contains the interrupt status for Timer4 */
#define AR_TIM_TIMER5INTSTATUS_OFFSET       0x74  /* Contains the interrupt status for Timer5 */
#define AR_TIM_TIMER6INTSTATUS_OFFSET       0x88  /* Contains the interrupt status for Timer6 */
#define AR_TIM_TIMER7INTSTATUS_OFFSET       0x9C  /* Contains the interrupt status for Timer7 */

#define AR_TIM_TIMERSINTSTATUS_OFFSET       0xA0  /* Timers Interrupt Status Register */
#define AR_TIM_TIMERSEOI_OFFSET             0xA4  /* Timers End-of-Interrupt Register */
#define AR_TIM_TIMERRAWINTSTATUS_OFFSET     0xA8  /* Timers Raw Interrupt Status Register */


#define AR_TIM0_TIMERLOADCOUNT_OFFSET               (AR_TIM0_BASE + AR_TIM_TIMER0LOADCOUNT_OFFSET)
#define AR_TIM1_TIMERLOADCOUNT_OFFSET               (AR_TIM0_BASE + AR_TIM_TIMER1LOADCOUNT_OFFSET)
#define AR_TIM2_TIMERLOADCOUNT_OFFSET               (AR_TIM0_BASE + AR_TIM_TIMER2LOADCOUNT_OFFSET)
#define AR_TIM3_TIMERLOADCOUNT_OFFSET               (AR_TIM0_BASE + AR_TIM_TIMER3LOADCOUNT_OFFSET)
#define AR_TIM4_TIMERLOADCOUNT_OFFSET               (AR_TIM0_BASE + AR_TIM_TIMER4LOADCOUNT_OFFSET)
#define AR_TIM5_TIMERLOADCOUNT_OFFSET               (AR_TIM0_BASE + AR_TIM_TIMER5LOADCOUNT_OFFSET)
#define AR_TIM6_TIMERLOADCOUNT_OFFSET               (AR_TIM0_BASE + AR_TIM_TIMER6LOADCOUNT_OFFSET)
#define AR_TIM7_TIMERLOADCOUNT_OFFSET               (AR_TIM0_BASE + AR_TIM_TIMER7LOADCOUNT_OFFSET)

#define AR_TIM10_TIMERLOADCOUNT_OFFSET              (AR_TIM1_BASE + AR_TIM_TIMER0LOADCOUNT_OFFSET)
#define AR_TIM11_TIMERLOADCOUNT_OFFSET              (AR_TIM1_BASE + AR_TIM_TIMER1LOADCOUNT_OFFSET)
#define AR_TIM12_TIMERLOADCOUNT_OFFSET              (AR_TIM1_BASE + AR_TIM_TIMER2LOADCOUNT_OFFSET)
#define AR_TIM13_TIMERLOADCOUNT_OFFSET              (AR_TIM1_BASE + AR_TIM_TIMER3LOADCOUNT_OFFSET)
#define AR_TIM14_TIMERLOADCOUNT_OFFSET              (AR_TIM1_BASE + AR_TIM_TIMER4LOADCOUNT_OFFSET)
#define AR_TIM15_TIMERLOADCOUNT_OFFSET              (AR_TIM1_BASE + AR_TIM_TIMER5LOADCOUNT_OFFSET)
#define AR_TIM16_TIMERLOADCOUNT_OFFSET              (AR_TIM1_BASE + AR_TIM_TIMER6LOADCOUNT_OFFSET)
#define AR_TIM17_TIMERLOADCOUNT_OFFSET              (AR_TIM1_BASE + AR_TIM_TIMER7LOADCOUNT_OFFSET)

#define AR_TIM20_TIMERLOADCOUNT_OFFSET              (AR_TIM2_BASE + AR_TIM_TIMER0LOADCOUNT_OFFSET)
#define AR_TIM21_TIMERLOADCOUNT_OFFSET              (AR_TIM2_BASE + AR_TIM_TIMER1LOADCOUNT_OFFSET)
#define AR_TIM22_TIMERLOADCOUNT_OFFSET              (AR_TIM2_BASE + AR_TIM_TIMER2LOADCOUNT_OFFSET)
#define AR_TIM23_TIMERLOADCOUNT_OFFSET              (AR_TIM2_BASE + AR_TIM_TIMER3LOADCOUNT_OFFSET)
#define AR_TIM24_TIMERLOADCOUNT_OFFSET              (AR_TIM2_BASE + AR_TIM_TIMER4LOADCOUNT_OFFSET)
#define AR_TIM25_TIMERLOADCOUNT_OFFSET              (AR_TIM2_BASE + AR_TIM_TIMER5LOADCOUNT_OFFSET)
#define AR_TIM26_TIMERLOADCOUNT_OFFSET              (AR_TIM2_BASE + AR_TIM_TIMER6LOADCOUNT_OFFSET)
#define AR_TIM27_TIMERLOADCOUNT_OFFSET              (AR_TIM2_BASE + AR_TIM_TIMER7LOADCOUNT_OFFSET)


#define AR_TIM0_TIMERLOADCOUNT2_OFFSET              (AR_TIM0_BASE + AR_TIM_TIMER0LOADCOUNT2_OFFSET)
#define AR_TIM1_TIMERLOADCOUNT2_OFFSET              (AR_TIM0_BASE + AR_TIM_TIMER1LOADCOUNT2_OFFSET)
#define AR_TIM2_TIMERLOADCOUNT2_OFFSET              (AR_TIM0_BASE + AR_TIM_TIMER2LOADCOUNT2_OFFSET)
#define AR_TIM3_TIMERLOADCOUNT2_OFFSET              (AR_TIM0_BASE + AR_TIM_TIMER3LOADCOUNT2_OFFSET)
#define AR_TIM4_TIMERLOADCOUNT2_OFFSET              (AR_TIM0_BASE + AR_TIM_TIMER4LOADCOUNT2_OFFSET)
#define AR_TIM5_TIMERLOADCOUNT2_OFFSET              (AR_TIM0_BASE + AR_TIM_TIMER5LOADCOUNT2_OFFSET)
#define AR_TIM6_TIMERLOADCOUNT2_OFFSET              (AR_TIM0_BASE + AR_TIM_TIMER6LOADCOUNT2_OFFSET)
#define AR_TIM7_TIMERLOADCOUNT2_OFFSET              (AR_TIM0_BASE + AR_TIM_TIMER7LOADCOUNT2_OFFSET)

#define AR_TIM10_TIMERLOADCOUNT2_OFFSET             (AR_TIM1_BASE + AR_TIM_TIMER0LOADCOUNT2_OFFSET)
#define AR_TIM11_TIMERLOADCOUNT2_OFFSET             (AR_TIM1_BASE + AR_TIM_TIMER1LOADCOUNT2_OFFSET)
#define AR_TIM12_TIMERLOADCOUNT2_OFFSET             (AR_TIM1_BASE + AR_TIM_TIMER2LOADCOUNT2_OFFSET)
#define AR_TIM13_TIMERLOADCOUNT2_OFFSET             (AR_TIM1_BASE + AR_TIM_TIMER3LOADCOUNT2_OFFSET)
#define AR_TIM14_TIMERLOADCOUNT2_OFFSET             (AR_TIM1_BASE + AR_TIM_TIMER4LOADCOUNT2_OFFSET)
#define AR_TIM15_TIMERLOADCOUNT2_OFFSET             (AR_TIM1_BASE + AR_TIM_TIMER5LOADCOUNT2_OFFSET)
#define AR_TIM16_TIMERLOADCOUNT2_OFFSET             (AR_TIM1_BASE + AR_TIM_TIMER6LOADCOUNT2_OFFSET)
#define AR_TIM17_TIMERLOADCOUNT2_OFFSET             (AR_TIM1_BASE + AR_TIM_TIMER7LOADCOUNT2_OFFSET)

#define AR_TIM20_TIMERLOADCOUNT2_OFFSET             (AR_TIM2_BASE + AR_TIM_TIMER0LOADCOUNT2_OFFSET)
#define AR_TIM21_TIMERLOADCOUNT2_OFFSET             (AR_TIM2_BASE + AR_TIM_TIMER1LOADCOUNT2_OFFSET)
#define AR_TIM22_TIMERLOADCOUNT2_OFFSET             (AR_TIM2_BASE + AR_TIM_TIMER2LOADCOUNT2_OFFSET)
#define AR_TIM23_TIMERLOADCOUNT2_OFFSET             (AR_TIM2_BASE + AR_TIM_TIMER3LOADCOUNT2_OFFSET)
#define AR_TIM24_TIMERLOADCOUNT2_OFFSET             (AR_TIM2_BASE + AR_TIM_TIMER4LOADCOUNT2_OFFSET)
#define AR_TIM25_TIMERLOADCOUNT2_OFFSET             (AR_TIM2_BASE + AR_TIM_TIMER5LOADCOUNT2_OFFSET)
#define AR_TIM26_TIMERLOADCOUNT2_OFFSET             (AR_TIM2_BASE + AR_TIM_TIMER6LOADCOUNT2_OFFSET)
#define AR_TIM27_TIMERLOADCOUNT2_OFFSET             (AR_TIM2_BASE + AR_TIM_TIMER7LOADCOUNT2_OFFSET)


#define AR_TIM0_TIMERCURRENTVALUE_OFFSET            (AR_TIM0_BASE + AR_TIM_TIMER0CURRENTVALUE_OFFSET)
#define AR_TIM1_TIMERCURRENTVALUE_OFFSET            (AR_TIM0_BASE + AR_TIM_TIMER1CURRENTVALUE_OFFSET)
#define AR_TIM2_TIMERCURRENTVALUE_OFFSET            (AR_TIM0_BASE + AR_TIM_TIMER2CURRENTVALUE_OFFSET)
#define AR_TIM3_TIMERCURRENTVALUE_OFFSET            (AR_TIM0_BASE + AR_TIM_TIMER3CURRENTVALUE_OFFSET)
#define AR_TIM4_TIMERCURRENTVALUE_OFFSET            (AR_TIM0_BASE + AR_TIM_TIMER4CURRENTVALUE_OFFSET)
#define AR_TIM5_TIMERCURRENTVALUE_OFFSET            (AR_TIM0_BASE + AR_TIM_TIMER5CURRENTVALUE_OFFSET)
#define AR_TIM6_TIMERCURRENTVALUE_OFFSET            (AR_TIM0_BASE + AR_TIM_TIMER6CURRENTVALUE_OFFSET)
#define AR_TIM7_TIMERCURRENTVALUE_OFFSET            (AR_TIM0_BASE + AR_TIM_TIMER7CURRENTVALUE_OFFSET)

#define AR_TIM10_TIMERCURRENTVALUE_OFFSET           (AR_TIM1_BASE + AR_TIM_TIMER0CURRENTVALUE_OFFSET)
#define AR_TIM11_TIMERCURRENTVALUE_OFFSET           (AR_TIM1_BASE + AR_TIM_TIMER1CURRENTVALUE_OFFSET)
#define AR_TIM12_TIMERCURRENTVALUE_OFFSET           (AR_TIM1_BASE + AR_TIM_TIMER2CURRENTVALUE_OFFSET)
#define AR_TIM13_TIMERCURRENTVALUE_OFFSET           (AR_TIM1_BASE + AR_TIM_TIMER3CURRENTVALUE_OFFSET)
#define AR_TIM14_TIMERCURRENTVALUE_OFFSET           (AR_TIM1_BASE + AR_TIM_TIMER4CURRENTVALUE_OFFSET)
#define AR_TIM15_TIMERCURRENTVALUE_OFFSET           (AR_TIM1_BASE + AR_TIM_TIMER5CURRENTVALUE_OFFSET)
#define AR_TIM16_TIMERCURRENTVALUE_OFFSET           (AR_TIM1_BASE + AR_TIM_TIMER6CURRENTVALUE_OFFSET)
#define AR_TIM17_TIMERCURRENTVALUE_OFFSET           (AR_TIM1_BASE + AR_TIM_TIMER7CURRENTVALUE_OFFSET)

#define AR_TIM20_TIMERCURRENTVALUE_OFFSET           (AR_TIM2_BASE + AR_TIM_TIMER0CURRENTVALUE_OFFSET)
#define AR_TIM21_TIMERCURRENTVALUE_OFFSET           (AR_TIM2_BASE + AR_TIM_TIMER1CURRENTVALUE_OFFSET)
#define AR_TIM22_TIMERCURRENTVALUE_OFFSET           (AR_TIM2_BASE + AR_TIM_TIMER2CURRENTVALUE_OFFSET)
#define AR_TIM23_TIMERCURRENTVALUE_OFFSET           (AR_TIM2_BASE + AR_TIM_TIMER3CURRENTVALUE_OFFSET)
#define AR_TIM24_TIMERCURRENTVALUE_OFFSET           (AR_TIM2_BASE + AR_TIM_TIMER4CURRENTVALUE_OFFSET)
#define AR_TIM25_TIMERCURRENTVALUE_OFFSET           (AR_TIM2_BASE + AR_TIM_TIMER5CURRENTVALUE_OFFSET)
#define AR_TIM26_TIMERCURRENTVALUE_OFFSET           (AR_TIM2_BASE + AR_TIM_TIMER6CURRENTVALUE_OFFSET)
#define AR_TIM27_TIMERCURRENTVALUE_OFFSET           (AR_TIM2_BASE + AR_TIM_TIMER7CURRENTVALUE_OFFSET)


#define AR_TIM0_TIMERCONTROLREG_OFFSET              (AR_TIM0_BASE + AR_TIM_TIMER0CONTROLREG_OFFSET)
#define AR_TIM1_TIMERCONTROLREG_OFFSET              (AR_TIM0_BASE + AR_TIM_TIMER1CONTROLREG_OFFSET)
#define AR_TIM2_TIMERCONTROLREG_OFFSET              (AR_TIM0_BASE + AR_TIM_TIMER2CONTROLREG_OFFSET)
#define AR_TIM3_TIMERCONTROLREG_OFFSET              (AR_TIM0_BASE + AR_TIM_TIMER3CONTROLREG_OFFSET)
#define AR_TIM4_TIMERCONTROLREG_OFFSET              (AR_TIM0_BASE + AR_TIM_TIMER4CONTROLREG_OFFSET)
#define AR_TIM5_TIMERCONTROLREG_OFFSET              (AR_TIM0_BASE + AR_TIM_TIMER5CONTROLREG_OFFSET)
#define AR_TIM6_TIMERCONTROLREG_OFFSET              (AR_TIM0_BASE + AR_TIM_TIMER6CONTROLREG_OFFSET)
#define AR_TIM7_TIMERCONTROLREG_OFFSET              (AR_TIM0_BASE + AR_TIM_TIMER7CONTROLREG_OFFSET)

#define AR_TIM10_TIMERCONTROLREG_OFFSET             (AR_TIM1_BASE + AR_TIM_TIMER0CONTROLREG_OFFSET)
#define AR_TIM11_TIMERCONTROLREG_OFFSET             (AR_TIM1_BASE + AR_TIM_TIMER1CONTROLREG_OFFSET)
#define AR_TIM12_TIMERCONTROLREG_OFFSET             (AR_TIM1_BASE + AR_TIM_TIMER2CONTROLREG_OFFSET)
#define AR_TIM13_TIMERCONTROLREG_OFFSET             (AR_TIM1_BASE + AR_TIM_TIMER3CONTROLREG_OFFSET)
#define AR_TIM14_TIMERCONTROLREG_OFFSET             (AR_TIM1_BASE + AR_TIM_TIMER4CONTROLREG_OFFSET)
#define AR_TIM15_TIMERCONTROLREG_OFFSET             (AR_TIM1_BASE + AR_TIM_TIMER5CONTROLREG_OFFSET)
#define AR_TIM16_TIMERCONTROLREG_OFFSET             (AR_TIM1_BASE + AR_TIM_TIMER6CONTROLREG_OFFSET)
#define AR_TIM17_TIMERCONTROLREG_OFFSET             (AR_TIM1_BASE + AR_TIM_TIMER7CONTROLREG_OFFSET)

#define AR_TIM20_TIMERCONTROLREG_OFFSET             (AR_TIM2_BASE + AR_TIM_TIMER0CONTROLREG_OFFSET)
#define AR_TIM21_TIMERCONTROLREG_OFFSET             (AR_TIM2_BASE + AR_TIM_TIMER1CONTROLREG_OFFSET)
#define AR_TIM22_TIMERCONTROLREG_OFFSET             (AR_TIM2_BASE + AR_TIM_TIMER2CONTROLREG_OFFSET)
#define AR_TIM23_TIMERCONTROLREG_OFFSET             (AR_TIM2_BASE + AR_TIM_TIMER3CONTROLREG_OFFSET)
#define AR_TIM24_TIMERCONTROLREG_OFFSET             (AR_TIM2_BASE + AR_TIM_TIMER4CONTROLREG_OFFSET)
#define AR_TIM25_TIMERCONTROLREG_OFFSET             (AR_TIM2_BASE + AR_TIM_TIMER5CONTROLREG_OFFSET)
#define AR_TIM26_TIMERCONTROLREG_OFFSET             (AR_TIM2_BASE + AR_TIM_TIMER6CONTROLREG_OFFSET)
#define AR_TIM27_TIMERCONTROLREG_OFFSET             (AR_TIM2_BASE + AR_TIM_TIMER7CONTROLREG_OFFSET)


#define AR_TIM0_TIMEREOI_OFFSET                     (AR_TIM0_BASE + AR_TIM_TIMER0EOI_OFFSET)
#define AR_TIM1_TIMEREOI_OFFSET                     (AR_TIM0_BASE + AR_TIM_TIMER1EOI_OFFSET)
#define AR_TIM2_TIMEREOI_OFFSET                     (AR_TIM0_BASE + AR_TIM_TIMER2EOI_OFFSET)
#define AR_TIM3_TIMEREOI_OFFSET                     (AR_TIM0_BASE + AR_TIM_TIMER3EOI_OFFSET)
#define AR_TIM4_TIMEREOI_OFFSET                     (AR_TIM0_BASE + AR_TIM_TIMER4EOI_OFFSET)
#define AR_TIM5_TIMEREOI_OFFSET                     (AR_TIM0_BASE + AR_TIM_TIMER5EOI_OFFSET)
#define AR_TIM6_TIMEREOI_OFFSET                     (AR_TIM0_BASE + AR_TIM_TIMER6EOI_OFFSET)
#define AR_TIM7_TIMEREOI_OFFSET                     (AR_TIM0_BASE + AR_TIM_TIMER7EOI_OFFSET)

#define AR_TIM10_TIMEREOI_OFFSET                    (AR_TIM1_BASE + AR_TIM_TIMER0EOI_OFFSET)
#define AR_TIM11_TIMEREOI_OFFSET                    (AR_TIM1_BASE + AR_TIM_TIMER1EOI_OFFSET)
#define AR_TIM12_TIMEREOI_OFFSET                    (AR_TIM1_BASE + AR_TIM_TIMER2EOI_OFFSET)
#define AR_TIM13_TIMEREOI_OFFSET                    (AR_TIM1_BASE + AR_TIM_TIMER3EOI_OFFSET)
#define AR_TIM14_TIMEREOI_OFFSET                    (AR_TIM1_BASE + AR_TIM_TIMER4EOI_OFFSET)
#define AR_TIM15_TIMEREOI_OFFSET                    (AR_TIM1_BASE + AR_TIM_TIMER5EOI_OFFSET)
#define AR_TIM16_TIMEREOI_OFFSET                    (AR_TIM1_BASE + AR_TIM_TIMER6EOI_OFFSET)
#define AR_TIM17_TIMEREOI_OFFSET                    (AR_TIM1_BASE + AR_TIM_TIMER7EOI_OFFSET)

#define AR_TIM20_TIMEREOI_OFFSET                    (AR_TIM2_BASE + AR_TIM_TIMER0EOI_OFFSET)
#define AR_TIM21_TIMEREOI_OFFSET                    (AR_TIM2_BASE + AR_TIM_TIMER1EOI_OFFSET)
#define AR_TIM22_TIMEREOI_OFFSET                    (AR_TIM2_BASE + AR_TIM_TIMER2EOI_OFFSET)
#define AR_TIM23_TIMEREOI_OFFSET                    (AR_TIM2_BASE + AR_TIM_TIMER3EOI_OFFSET)
#define AR_TIM24_TIMEREOI_OFFSET                    (AR_TIM2_BASE + AR_TIM_TIMER4EOI_OFFSET)
#define AR_TIM25_TIMEREOI_OFFSET                    (AR_TIM2_BASE + AR_TIM_TIMER5EOI_OFFSET)
#define AR_TIM26_TIMEREOI_OFFSET                    (AR_TIM2_BASE + AR_TIM_TIMER6EOI_OFFSET)
#define AR_TIM27_TIMEREOI_OFFSET                    (AR_TIM2_BASE + AR_TIM_TIMER7EOI_OFFSET)


#define AR_TIM0_TIMERINTSTATUS_OFFSET               (AR_TIM0_BASE + AR_TIM_TIMER0INTSTATUS_OFFSET)
#define AR_TIM1_TIMERINTSTATUS_OFFSET               (AR_TIM0_BASE + AR_TIM_TIMER1INTSTATUS_OFFSET)
#define AR_TIM2_TIMERINTSTATUS_OFFSET               (AR_TIM0_BASE + AR_TIM_TIMER2INTSTATUS_OFFSET)
#define AR_TIM3_TIMERINTSTATUS_OFFSET               (AR_TIM0_BASE + AR_TIM_TIMER3INTSTATUS_OFFSET)
#define AR_TIM4_TIMERINTSTATUS_OFFSET               (AR_TIM0_BASE + AR_TIM_TIMER4INTSTATUS_OFFSET)
#define AR_TIM5_TIMERINTSTATUS_OFFSET               (AR_TIM0_BASE + AR_TIM_TIMER5INTSTATUS_OFFSET)
#define AR_TIM6_TIMERINTSTATUS_OFFSET               (AR_TIM0_BASE + AR_TIM_TIMER6INTSTATUS_OFFSET)
#define AR_TIM7_TIMERINTSTATUS_OFFSET               (AR_TIM0_BASE + AR_TIM_TIMER7INTSTATUS_OFFSET)

#define AR_TIM10_TIMERINTSTATUS_OFFSET              (AR_TIM1_BASE + AR_TIM_TIMER0INTSTATUS_OFFSET)
#define AR_TIM11_TIMERINTSTATUS_OFFSET              (AR_TIM1_BASE + AR_TIM_TIMER1INTSTATUS_OFFSET)
#define AR_TIM12_TIMERINTSTATUS_OFFSET              (AR_TIM1_BASE + AR_TIM_TIMER2INTSTATUS_OFFSET)
#define AR_TIM13_TIMERINTSTATUS_OFFSET              (AR_TIM1_BASE + AR_TIM_TIMER3INTSTATUS_OFFSET)
#define AR_TIM14_TIMERINTSTATUS_OFFSET              (AR_TIM1_BASE + AR_TIM_TIMER4INTSTATUS_OFFSET)
#define AR_TIM15_TIMERINTSTATUS_OFFSET              (AR_TIM1_BASE + AR_TIM_TIMER5INTSTATUS_OFFSET)
#define AR_TIM16_TIMERINTSTATUS_OFFSET              (AR_TIM1_BASE + AR_TIM_TIMER6INTSTATUS_OFFSET)
#define AR_TIM17_TIMERINTSTATUS_OFFSET              (AR_TIM1_BASE + AR_TIM_TIMER7INTSTATUS_OFFSET)

#define AR_TIM20_TIMERINTSTATUS_OFFSET              (AR_TIM2_BASE + AR_TIM_TIMER0INTSTATUS_OFFSET)
#define AR_TIM21_TIMERINTSTATUS_OFFSET              (AR_TIM2_BASE + AR_TIM_TIMER1INTSTATUS_OFFSET)
#define AR_TIM22_TIMERINTSTATUS_OFFSET              (AR_TIM2_BASE + AR_TIM_TIMER2INTSTATUS_OFFSET)
#define AR_TIM23_TIMERINTSTATUS_OFFSET              (AR_TIM2_BASE + AR_TIM_TIMER3INTSTATUS_OFFSET)
#define AR_TIM24_TIMERINTSTATUS_OFFSET              (AR_TIM2_BASE + AR_TIM_TIMER4INTSTATUS_OFFSET)
#define AR_TIM25_TIMERINTSTATUS_OFFSET              (AR_TIM2_BASE + AR_TIM_TIMER5INTSTATUS_OFFSET)
#define AR_TIM26_TIMERINTSTATUS_OFFSET              (AR_TIM2_BASE + AR_TIM_TIMER6INTSTATUS_OFFSET)
#define AR_TIM27_TIMERINTSTATUS_OFFSET              (AR_TIM2_BASE + AR_TIM_TIMER7INTSTATUS_OFFSET)


#define AR_TIM0_TIMERSINTSTATUS_OFFSET              (AR_TIM0_BASE + AR_TIM_TIMERSINTSTATUS_OFFSET)
#define AR_TIM1_TIMERSINTSTATUS_OFFSET              (AR_TIM1_BASE + AR_TIM_TIMERSINTSTATUS_OFFSET)
#define AR_TIM2_TIMERSINTSTATUS_OFFSET              (AR_TIM2_BASE + AR_TIM_TIMERSINTSTATUS_OFFSET)


#define AR_TIM0_TIMERSEOI_OFFSET                    (AR_TIM0_BASE + AR_TIM_TIMERSEOI_OFFSET)
#define AR_TIM1_TIMERSEOI_OFFSET                    (AR_TIM1_BASE + AR_TIM_TIMERSEOI_OFFSET)
#define AR_TIM2_TIMERSEOI_OFFSET                    (AR_TIM2_BASE + AR_TIM_TIMERSEOI_OFFSET)


#define AR_TIM0_TIMERRAWINTSTATUS_OFFSET            (AR_TIM0_BASE + AR_TIM_TIMERRAWINTSTATUS_OFFSET)
#define AR_TIM1_TIMERRAWINTSTATUS_OFFSET            (AR_TIM1_BASE + AR_TIM_TIMERRAWINTSTATUS_OFFSET)
#define AR_TIM2_TIMERRAWINTSTATUS_OFFSET            (AR_TIM2_BASE + AR_TIM_TIMERRAWINTSTATUS_OFFSET)


#define AR_TIMERCONTROLREG_PWM                      (1 << 3)
#define AR_TIMERCONTROLREG_PWM_ENABLE               (1 << 3)
#define AR_TIMERCONTROLREG_PWM_DISABLE              (0 << 3)

#define AR_TIMERCONTROLREG_INTMASK                  (1 << 2)
#define AR_TIMERCONTROLREG_INTMASK_MASKED           (1 << 2)
#define AR_TIMERCONTROLREG_INTMASK_NOMASKED         (0 << 2)

#define AR_TIMERCONTROLREG_MODE                     (1 << 1)
#define AR_TIMERCONTROLREG_MODE_USERDEFINED         (1 << 1)
#define AR_TIMERCONTROLREG_MODE_FREERUN             (0 << 1)
 
#define AR_TIMERCONTROLREG_ENABLE                   (1 << 0)
#define AR_TIMERCONTROLREG_ENABLE_ENABLE            (1 << 0)
#define AR_TIMERCONTROLREG_ENABLE_DISABLE           (0 << 0)



#endif /* __ARCH_ARM_SRC_ARTOSYN_CHIP_AR_TIM_H */
